# Generated by Django 6.0.2 on 2026-02-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handovers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handover',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='handover',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
