# Generated by Django 5.0.4 on 2026-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handovers', '0002_handover_is_completed_handover_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
