# Generated by Django 6.0.2 on 2026-02-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careplan',
            old_name='description',
            new_name='assessment_summary',
        ),
        migrations.AddField(
            model_name='careplan',
            name='communication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='daily_routine',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='medication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='mobility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='nutrition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='personal_care',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='safeguarding_risks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='skin_integrity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='wellbeing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='title',
            field=models.CharField(blank=True, default='Care Plan', max_length=200),
        ),
    ]
