# Generated by Django 5.0.4 on 2026-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplans', '0002_remove_careplan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careplan',
            name='assessment_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
