# Generated by Django 6.0.2 on 2026-02-20 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_RESIDENT', 'Created Resident'), ('UPDATE_RESIDENT', 'Updated Resident'), ('ARCHIVE_RESIDENT', 'Archived Resident'), ('UNARCHIVE_RESIDENT', 'Unarchived Resident'), ('DELETE_RESIDENT', 'Deleted Resident'), ('CREATE_CAREPLAN', 'Created Care Plan'), ('UPDATE_CAREPLAN', 'Updated Care Plan'), ('ARCHIVE_CAREPLAN', 'Archived Care Plan'), ('UNARCHIVE_CAREPLAN', 'Unarchived Care Plan'), ('CREATE_HANDOVER', 'Created Handover'), ('UPDATE_HANDOVER', 'Updated Handover'), ('COMPLETE_HANDOVER', 'Completed Handover'), ('CREATE_INCIDENT', 'Created Incident'), ('UPDATE_INCIDENT', 'Updated Incident'), ('RESOLVE_INCIDENT', 'Resolved Incident'), ('USER_APPROVAL', 'User Approved')], max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
