# Generated by Django 5.0.4 on 2026-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
